### PR TITLE
Update for android 8.1

### PR DESCRIPTION
**Pull request by chautruongthinh**

### CODE REVIEW

**Comment by bigbiff** [comment]
Hello, this will need to be pushed to the project at gerrit.twrp.me.

**Comment by chautruongthinh** [comment]
ef63 device is no longer on gerrit so i cant push to gerrit

**Comment by bigbiff** [comment]
It's recreated. Sorry for the inconvenience.

**Comment by chautruongthinh** [comment]
Can you help me to creat branch android-8.1 or you canset  permisson for me, i will creat new branch

**Pull request closed without merging**
